@Ambev.DeveloperEvaluation.WebApi_HostAddress = http://localhost:8080

### Get a user by ID
GET http://localhost:8080/api/Users/f8a13e8c-f4ac-4c93-b778-601790e4f5f3
Accept: application/json

### Create a new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "JohnDoe",
  "email": "johndoe@example.com",
  "phone": "11994730392",
  "password": "Password@123",
  "role": 1,
  "status": 1
}

### Delete a user
DELETE http://localhost:8080/api/Users/f8a13e8c-f4ac-4c93-b778-601790e4f5f3
Accept: application/json