@Ambev.DeveloperEvaluation.WebApi_HostAddress = http://localhost:8080

### Get a user by ID
GET http://localhost:8080/api/Users/dd8e9ee7-0eff-4f24-a518-6d838c8e5edf
Accept: application/json

### Create a new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "JohnDoe",
  "email": "johndoe@example.com",
  "phone": "11994730392",
  "password": "Password@123",
  "role": 1,
  "status": 1
}

### Delete a user
DELETE http://localhost:8080/api/Users/dd8e9ee7-0eff-4f24-a518-6d838c8e5edf
Accept: application/json


### Authenticate a user
POST http://localhost:8080/api/Auth
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "Password@123"
}