networks:
  developerevaluation_network:
    driver: bridge

services:
  ambev.developerevaluation.webapi:
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    container_name: ambev_developer_evaluation_webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${USER_SECRETS_PATH}:/home/app/.microsoft/usersecrets:ro
      - ${HTTPS_PATH}:/home/app/.aspnet/https:ro
    depends_on:
      ambev.developerevaluation.database:
        condition: service_healthy
    networks:
      - developerevaluation_network
  
  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    tty: true
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d developer_evaluation" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - developerevaluation_network
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker/rabbitmq/init.sh:/init.sh
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    command: >
      bash -c "
        docker-entrypoint.sh rabbitmq-server &
        sleep 30 &&
        chmod +x /init.sh &&
        /init.sh && wait
      "
    networks:
      - developerevaluation_network

volumes:
  rabbitmq_data:
