networks:
  developerevaluation_network:
    driver: bridge

services:
  ambev.developerevaluation.webapi:
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    container_name: ambev_developer_evaluation_webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${USER_SECRETS_PATH}:/home/app/.microsoft/usersecrets:ro
      - ${HTTPS_PATH}:/home/app/.aspnet/https:ro
    depends_on:
      ambev.developerevaluation.database:
        condition: service_healthy
    networks:
      - developerevaluation_network
  
  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:13

    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5432:5432"
    restart: always
    tty: true
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d developer_evaluation" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - developerevaluation_network